name: Sync Fork

on:
  schedule:
    - cron: '5 */12 * * *' # At minute 5 past every 12th hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: llvm
          base: master
          head: master
